### ISSUE TITLE
display the image from the debug console?

### ISSUE THREAD

**Issue by seyeeet** [john-guo/simply-view-image-for-python-opencv-debugging#11]
thanks for this extension this is amazing.
Would it be also possible to make it to be able to display the image when I do it in debug console.
I mean, lets say i have:
```
import torch as np
img = np.random.rand(100,100,3)
```
now I just can display the image (`img`) in the main file. would it be possible that I copy and paste `np.random.rand(100,100,3)` in the debug console like `simple_view(np.random.rand(100,100,3))` and it display the image. `simple_view` is gonna be a function from your code that you tell us to run to see the image.

Thanks for this extension anyways :)

**Comment by john-guo** [comment]
Thanks for using this extension.  But this extension is not a debugger extension, so it cannot read any information from the debug console. It just provides a standard extension command that you can press F1 to invoke. If you need to view an image with the debug console, I suggest you can create an image exporting method such as "simple_view(img)"  in your main.py, suppose this method will save the image as a certain filename, then you can call this method in the debug console, after all, keep the saved file open to view the image.
