### ISSUE TITLE
The extension has stopped working for me

### ISSUE THREAD

**Issue by saeedizadi** [john-guo/simply-view-image-for-python-opencv-debugging#14]
Hello, 

The extension was working amazing a couple weeks ago and now it has stopped working. 
When I select the image variable, it doesn't show up the light bulb for image view. 

VScode version: 1.63 (November)

**Comment by john-guo** [comment]
Hi,

I need more info to resolve this issue:

Try debug this Python code to show the image of the variable 'test'

`test = (img.numpy() * 255.0 if (hasattr(img, 'dtype')) and (img.dtype == np.float64 or img.dtype == np.float32) else img.numpy()) if callable(getattr(img, 'numpy', None)) else (img * 255.0 if (isinstance(img, (np.ndarray)) and (img.dtype == np.float64 or img.dtype == np.float32)) else img)`

The img is the image variable

Copy the log of debug window if there's any error,

and the Output Log(Extension Host)
![image](https://user-images.githubusercontent.com/7485003/151472501-2b17afc7-453c-4dc2-aeb1-3c03d78ca06c.png)

Thank you.

**Comment by john-guo** [comment]
Cannot reproduce
