### ISSUE TITLE
Why I can't use the extension independently?

### ISSUE THREAD

**Issue by realgump** [john-guo/simply-view-image-for-python-opencv-debugging#17]
Hello, thanks for your great extension that help me a lot. However, the extension seems doesn't work correctly. 

I have tried 2 image-debugging extensions, this one and another [python-image-preview](https://github.com/076923/python-image-preview), and strange things happen:

When I only enable this extension, there is no lightbulb when I debug.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/37771769/193200631-10464e98-8dff-4427-84ce-75cab5a63e19.png">

While I enable both this extension and the [python-image-preview](https://github.com/076923/python-image-preview), the two extensions work well.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/37771769/193187630-c14e091f-5446-4636-bb91-4a35bb2edd63.png">

So where is the problem?

**Comment by john-guo** [comment]
It seems you forgot to add the "import numpy as np". The [python-image-preview](https://github.com/076923/python-image-preview) perhaps implicitly import the numpy when it evaluate the python variable.

**Comment by realgump** [comment]
I have tried adding "import numpy as np", but nothing happened, and there is still no lightbulb. 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/37771769/194817344-db63c60e-6423-485b-9b4d-a85f418658c0.png">

**Comment by john-guo** [comment]
Perhaps there are some exception occurred. Could you paste your Output Log(Extension Host) where is located like the one shown in the picture.
![image](https://user-images.githubusercontent.com/7485003/194873859-73307c1c-7892-4cca-9582-0368196fa53a.png)

**Comment by john-guo** [comment]
Cannot reproduce
