### ISSUE TITLE
Extension not working via ssh with x11 forwarding

### ISSUE THREAD

**Issue by garrofederico** [john-guo/simply-view-image-for-python-opencv-debugging#18]
Hi John! Thanks for this great extension!

I have one problem though, it doesn't seem to we working when I'm connecting via SSH to a server and use X11 Forwarding. I can see the images when I run `cv2.imshow()` but I don't get the the preview option when hovering on the image variable.

**Comment by john-guo** [comment]
Hi, Could you paste some logs in Output Log(Extension Host)? I had only tested this extension in windows.

**Comment by john-guo** [comment]
Cannot reproduce
