### ISSUE TITLE
Can not show the image during debugging the python code.

### ISSUE THREAD

**Issue by zhfkt** [john-guo/simply-view-image-for-python-opencv-debugging#6]
Hi,

I am debugging the remote python code through wsl, and the plugin can not show the image during debugging the python code.

The logs says:

[2021-01-22 11:53:54.619] [exthost] [error] [johnguo.simply-view-image-for-python-opencv-debugging] provider FAILED
[2021-01-22 11:53:54.627] [exthost] [error] Error: Unable to find thread to evaluate variable reference.
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/SHData/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3369:750)
    at file:///C:/Users/SHData/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3369:55

![image](https://user-images.githubusercontent.com/4969804/105444473-dd2e6b00-5ca8-11eb-8443-7cd302426c7f.png)

Pls review. 

Thank you !

**Comment by john-guo** [comment]
Hello,

I have tested with wsl and it's no problem. Do you install the extension in wsl? The extension must be installed in wsl not local if you want to debug in wsl. 

![screenshot 2021-01-22 235529](https://user-images.githubusercontent.com/7485003/105513527-64152f00-5d0d-11eb-87b1-445fe26df2e7.png)

**Comment by zhfkt** [comment]
Hi @john-guo 

I installed the extension in both local and wsl env

![image](https://user-images.githubusercontent.com/4969804/105686219-f564eb00-5f31-11eb-8bc8-1d2bd759f074.png)

Could we have some way to collect extension logs for what happened in my local envs ? then I could provide extension  logs to you for futher debugging ?

**Comment by john-guo** [comment]
How do you start the debug? Could you paste some Python Debug Console outputs? Could you create a tiny python to test this issue, such as:

```
import numpy as np
import cv2

img = cv2.imread("test.jpg")

pass
```

or you can add some logs in ViewImageService.ts:

```
		let res = await session.customRequest('threads', {});
--------> console.log(res); 
		let threads = res.threads;
		let mainThread = threads[0].id;
--------> console.log(`main:${mainThread}`);
```

But I don't know if this will be helpful.

**Comment by zhfkt** [comment]
Hi @john-guo 

Thank you for your the suggestion. I just saw the log from the "Log (Remote Extension)" in the output window in the following screenshot


![image](https://user-images.githubusercontent.com/4969804/106453154-d59a6d80-64c3-11eb-9742-bfd92622e3f3.png)


Unfortunately I didn't have much time to debug further because I was too busy in recent days. I used another plugin from Pycharm on https://plugins.jetbrains.com/plugin/14371-opencv-image-viewer as an alternative choice. You could close this issue if you would like to close it.

**Comment by john-guo** [comment]
Hi zhfkt

It seems this issue is caused by multi-threading. Because the vscode debug api cannot provide the current thread id in active debug session, I use the first thread id to evaluate the expression. I will modify the limition description in ReadMe.Thank you.

**Comment by john-guo** [comment]
Hi @zhfkt

After some experimentation I made a workaround in multithreaded debugging. Hope it works for  you. Thank you.
