### ISSUE TITLE
can you make it to do the same thing for plt during the debug?

### ISSUE THREAD

**Issue by seyeeet** [john-guo/simply-view-image-for-python-opencv-debugging#7]

**Comment by john-guo** [comment]
hi, this extension was maked only for python opencv. The plt is different with opencv but I think you can make a new extension from this to archieve your purpose. For simply work, you can just use 'plt.savefig' to make it if you import pyplot as plt:

change ViewImageService.ts line 57-59:
`		
                const vn = targetVariable.evaluateName; // var name

		const float_expression =  `${vn} * 255.0 if (isinstance(${vn}, (np.ndarray)) and (${vn}.dtype == np.float64 or ${vn}.dtype == np.float32)) else ${vn}`;

		const expression = `cv2.imwrite('${savepath}', ${float_expression})`;

`
to
`
		const expression = `plt.savefig('${savepath}')`;
`
Then this new extension will work for plt.
